@baseUrl = https://be-tan-theta.vercel.app

### Get all categories
GET {{baseUrl}}/api/categories
Authorization: Bearer 1234

###

### Create category
POST {{baseUrl}}/api/categories
Content-Type: application/json
Authorization: Bearer 1234

{
  "categoryName": "Main Course",
  "priority": -1,
  "createdAt": "11-05-2025",
}

###

### Update category
PUT {{baseUrl}}/api/categories/68205bf5f94da516687c5921
Content-Type: application/json
Authorization: Bearer 1234

{
  "categoryName": "Updated Main Course"
}

###

### Delete category
DELETE http://localhost:3000/api/categories/68205bf5f94da516687c5921
Authorization: Bearer 1234
