@localUrl = http://localhost:5000
@baseUrl = https://be-tan-theta.vercel.app

### Get translation for text
POST {{localUrl}}/api/ai/translate
Authorization: Bearer 1234
Content-Type: application/json

{
  "text": "Casseroles",
  "targetLanguage": "he"
}

###

### Create picture from text
POST {{localUrl}}/api/ai/image
Authorization: Bearer 1234
Content-Type: application/json

{
  "text": "flowers in a field"
}

### Create text for recipe from title
POST {{localUrl}}/api/ai/fill-recipe
Authorization: Bearer 1234
Content-Type: application/json

{
  "recipeId": "6824b89071230ea2707f2280",
  "categoryName": "Pizzas",
  "targetLanguage": "en"
}